---@description The `` works as string to hash converter, avoid using "" or ''
return {
    [`airtug`] = true,
    [`apc`] = true,
    [`barracks`] = true,
    [`barracks2`] = true,
    [`barracks3`] = true,
    [`barrage`] = true,
    [`blimp`] = true,
    [`chernobog`] = true,
    [`crusader`] = true,
    [`halftrack`] = true,
    [`jet`] = true,
    [`khanjali`] = true,
    [`lazer`] = true,
    [`luxor`] = true,
    [`luxor2`] = true,
    [`minitank`] = true,
    [`rhino`] = true,
    [`ripley`] = true,
    [`scarab`] = true,
    [`scarab2`] = true,
    [`scarab3`] = true,
    [`shamal`] = true,
    [`thruster`] = true,
    [`titan`] = true,
    [`trailersmall2`] = true,
    [`vetir`] = true,
}